In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
dataset = pd.read_csv('dataset1.csv')
dataset = dataset.apply(pd.to_numeric,errors='coerce')
dataset

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,2,1,0,1,0,0,0,0,0,1,0,29.85,29.85,0
1,1,0,0,0,34,1,0,1,1,0,1,0,0,0,1,0,1,56.95,1889.50,0
2,1,0,0,0,2,1,0,1,1,1,0,0,0,0,0,1,1,53.85,108.15,1
3,1,0,0,0,45,0,2,1,1,0,1,1,0,0,1,0,2,42.30,1840.75,0
4,0,0,0,0,2,1,0,2,0,0,0,0,0,0,0,1,0,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,1,1,0,1,1,1,1,1,1,1,84.80,1990.50,0
7039,0,0,1,1,72,1,1,2,0,1,1,0,1,1,1,1,3,103.20,7362.90,0
7040,0,0,1,1,11,0,2,1,1,0,0,0,0,0,0,1,0,29.60,346.45,0
7041,1,1,1,0,4,1,1,2,0,0,0,0,0,0,0,1,1,74.40,306.60,1
7042,1,0,0,0,66,1,0,2,1,0,1,1,1,1,2,1,2,105.65,6844.50,0

In [3]:
dataset.describe()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7032.000000,7043.000000
mean,0.504756,0.162147,0.483033,0.299588,32.371149,0.903166,0.615505,1.222916,0.720006,0.778220,0.777226,0.723555,0.817691,0.821241,0.690473,0.592219,1.315633,64.761692,2283.300441,0.265370
std,0.500013,0.368612,0.499748,0.458110,24.559481,0.295752,0.656039,0.778877,0.796885,0.778472,0.778826,0.795896,0.763212,0.761725,0.833755,0.491457,1.148907,30.090047,2266.771362,0.441561
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.250000,18.800000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,9.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.500000,401.450000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,29.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,70.350000,1397.475000,0.000000
75%,1.000000,0.000000,1.000000,1.000000,55.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,89.850000,3794.737500,1.000000
max,1.000000,1.000000,1.000000,1.000000,72.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,3.000000,118.750000,8684.800000,1.000000

In [4]:
dataset_norm = dataset.copy()
for column in dataset_norm.columns:
    dataset_norm[column] = (dataset_norm[column] - dataset_norm[column].mean())  / dataset_norm[column].std()

In [5]:
dataset_x=dataset_norm.drop('Churn',axis=1)
dataset_x.head(5)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,-1.009487,-0.439885,1.034457,-0.653965,-1.277354,-3.053794,2.110385,-0.286202,-0.903525,0.284892,-0.997945,-0.909107,-1.071381,-1.078133,-0.828148,0.829739,-1.145117,-1.160241,-0.994123
1,0.990462,-0.439885,-0.966554,-0.653965,0.066323,0.327415,-0.938214,-0.286202,0.351361,-0.999676,0.286039,-0.909107,-1.071381,-1.078133,0.371245,-1.205028,-0.274724,-0.259611,-0.173727
2,0.990462,-0.439885,-0.966554,-0.653965,-1.236636,0.327415,-0.938214,-0.286202,0.351361,0.284892,-0.997945,-0.909107,-1.071381,-1.078133,-0.828148,0.829739,-0.274724,-0.362635,-0.959581
3,0.990462,-0.439885,-0.966554,-0.653965,0.514215,-3.053794,2.110385,-0.286202,0.351361,-0.999676,0.286039,0.347338,-1.071381,-1.078133,0.371245,-1.205028,0.595668,-0.746482,-0.195234
4,-1.009487,-0.439885,-0.966554,-0.653965,-1.236636,0.327415,-0.938214,0.997698,-0.903525,-0.999676,-0.997945,-0.909107,-1.071381,-1.078133,-0.828148,0.829739,-1.145117,0.197351,-0.940391

In [6]:
dataset_y=dataset_norm['Churn']
dataset_y.head(5)

0   -0.600981
1   -0.600981
2    1.663710
3   -0.600981
4    1.663710
Name: Churn, dtype: float64

In [7]:
train_x,test_x,train_y,test_y=train_test_split(dataset_x,dataset_y,test_size=0.2)

In [8]:
train_x.shape

(5634, 19)

In [9]:
test_x.shape

(1409, 19)

In [10]:
train_y.shape

(5634,)

In [11]:
test_y.shape

(1409,)